### ISSUE TITLE
Código de barras

### ISSUE THREAD

**Issue by seventechsolucoes** [paseto/boleto-sicredi#4]
Estou homologando os boletos com o pessoal da Sicredi porém, o código de barras não passa de nenhum jeito, todo o resto passa no verificador deles.

O projeto ainda recebe atualizações ?

**Comment by paseto** [comment]
Olá, @guilherme00 
Estou utilizando sem problemas, ontem mesmo efetuei teste e está funcionando normalmente.
O projeto recebe atualizações caso queira colaborar.
Obrigado.
