### ISSUE TITLE
Gerar Carnê

### ISSUE THREAD

**Issue by LucasSalicano** [paseto/boleto-sicredi#5]
Boa tarde, eu consegueria alterar o design e fazer emissão de carne ?

**Comment by paseto** [comment]
Olá @LucasSalicano ,
Você precisa criar uma nova classe parecida com essa para aceitar carnê:
https://github.com/moveis-simonetti/php-boleto-pdf/blob/master/src/Simonetti/Boleto/Carne/Parcela.php

**Comment by decosiqueira** [comment]
Boa tarde, estou justamente precisando de um sistema que gere boletos registrados para a Sicredi, já tenho a parte que faz a inscrições, agora precisaria gerar o boleto, sua rotina funciona para boletos registrados, e como rodo ela, para mim está dando erro nas classes.

**Comment by paseto** [comment]
Olá, o pacote não gera boleto em carnê.
Se houver alguma dificuldade especifique o problema encontrado abrindo uma nova issue.
